### ISSUE TITLE
URL routing using SitefinityRoute does not work with Sitefinity Feather

### ISSUE THREAD

**Issue by kyleballard** [Sitefinity/feather#77] opened 2014-12-18 21:53 UTC
Listed at this url is an example of how Sitefinity is able to be extended to support custom url routing.
http://www.sitefinity.com/developer-network/forums/developing-with-sitefinity-/url-routing

This works in non-feather projects, however we did encounter a bug when we were logged into the backend which occurred here: Telerik.Sitefinity.Web.UI.ScriptManagerWrapper.Page_InitComplete.  We were able to get around this by disabling the in-line editor inside Administration > Settings > Pages > "Enable in-line editing." = false.  I only note this so that if someone else runs across this, it may help them.

Additionally, for Feather projects, users may encounter a blank page when attempting to render a custom route.  I believe the issue can be traced to this file:  https://github.com/Sitefinity/feather/blob/master/Telerik.Sitefinity.Frontend/Resources/PackageManager.cs#L35 which obtains the current resource package.  The method inspects both the Url and the PageInfo to obtain the current package, neither of which exist if you are using a virtual route (i.e. /my/custom/route/to/whatever)

As a result, the AddVariablesToPath() method inside LayoutVirtualPathBuilder.cs never applies the resource package (i.e. Bootstrap) to the virtual path. This in turn results in GetVirtualPath(IPageTemplate template) to return null because the layout is said not to exist.

To work around this, without making modifications to Telerik.Sitefinity.Frontend assembly, I was able to inject the following line of code in my method which returns RouteData just before my call to this.GetRouteDataInternal()  [this assumes I am using Bootstrap for this instance].  

SystemManager.CurrentHttpContext.Items["CurrentResourcePackage"] = "Bootstrap";

Finally, one last error I ran into, was despite disabling in-line editing as noted above, the following line in the default Bootstrap template caused a NullReferenceException when LayoutRenderer.RenderViewToString made a call to Render() the razor view:
@Html.InlineEditingManager(false)

Once I removed this line, the NullReferenceException was avoided, and the view rendered properly for my custom routes.

Hope this helps!

**Comment by mariushm** [comment] 2015-01-15 15:27
Hi Kyle,

Thank you very much for the detailed description. We have reviewed it thoroughly and logged several fixes to include in the upcoming releases.

**Comment by kyleballard** [comment] 2015-02-19 19:39
Hi Mariush - 

I upgraded Feather to v1.1.80.1 and am still experiencing the issue.  I still, unfortunately, need to use the workaround described above.  Further, I need to make a request to the actual Sitefinity page I am routing to before any of the routes would work.  In an example, if I wanted to map and intercept requests and re-route them to a tangible Sitefinity page "/store-item?routed-querystring=value" I first have to make a request to "/store-item" or an error occurs.  I believe this is due to a caching mechanism that it does not detect "/store-item" until the page has been requested at least once.

I'd like to motion this issue be re-opened as I do not believe it has been resolved in the latest version 1.1.80.

**Comment by mariushm** [comment] 2015-02-20 09:41
Hi Kyle,

We have logged 3 different bugs based on your original post and so far fixed only one of them. So indeed, the problem was not resolved. We will keep this issue open until it is fully resolved.

Mariush

**Comment by Boyko-Karadzhov** [comment] 2015-03-21 15:52
Hello Kyle,

I managed to reproduce all the issues that you have described using a custom SitefinityRoute implementation much like the one in the [forum post](http://www.sitefinity.com/developer-network/forums/developing-with-sitefinity-/url-routing). A lot of code breaks because information about the current node is missing. To fix that all you need to do is call SetRequestVariables before returning route data. See the code bellow.

```CSharp
var node = sitemapProvider.FindSiteMapNode("path", false, out isAdditional, out pars) as PageSiteNode;
if (node != null)
{
    this.SetRequestVariables(httpContext, sitemapProvider, node);
    return this.GetRouteDataInternal(pars, httpContext.Request.QueryString, node);
}
```

Regards,
Boyko

**Comment by kyleballard** [comment] 2015-03-23 18:22
Thanks.  We also found that the issue was resolved in version 8.  I'm not sure if another change inadvertently fixed this as well, but so far the issue has resolved.  We still have to disable in-line editing, but other than that it's ok.  I will report back if it continues.

Thank you for the additional information regarding obtaining the current node.

**Closed** 2015-03-26 10:33 UTC
Labels: bug, customer submitted, dev, t2

**Comment by poebrand** [comment] 2016-12-09 03:21
This issue has returned in Sitefinity version 9.2.
