### ISSUE TITLE
Script tags are added outside the closing body tag

### ISSUE THREAD

**Issue by JenPeleva** [Sitefinity/feather#1452] opened 2015-04-24 08:48 UTC
This happens with Feather pages only and leads to validation errors.

**Comment by Boyko-Karadzhov** [comment] 2015-04-24 11:44
The issue is in the way Sitefinity adds the Stats scripts. It is fixed in an internal build after Sitefinity 8.0.

**Closed** 2015-04-24 11:45 UTC
Labels: bug, severity: high, t2
