### ISSUE TITLE
Image Selector: tooltip does not work on SemanticUI page

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#668] opened 2015-02-17 15:40 UTC
Steps to reproduce:
1. create page based on SemanticUI template and drop Content block
2. open image selector
3. hover over an image
As a result: tooltip is not fired
Reproducible in all browsers

**Comment by dpanov** [comment] 2015-02-17 16:18
Tested in Chrome and Firefox and I couldn't reproduce it. 
It was probably fixed in the meantime.  :-)

**Closed** 2015-02-18 08:09 UTC
Labels: bug, severity: medium, ux
