### ISSUE TITLE
Subscribe form: On Bootstrap page, Js error message appears if you press Subscribe in Inline editing mode

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#2033] opened 2015-06-17 14:42 UTC
1. D&D Subscribe form or Unsubscribe ( with Email Address selected ) widget on Bootstrap page
2. On frontend select Inline editing
3. Enter valid or invalid mail
4. Press Subscribe ( Unsubscribe )
   Note that js error appears:
   http://screencast.com/t/dMOeqzalrmOL

**Comment by PepiIvanova** [comment] 2015-06-18 06:46
All MVC widgets (Registration, Login form, Subscribe, Profile and etc.) having inputs in the view throw exception in Inline Editing mode (the exception is thrown when switching to Inline editing mode). It seems the issue is in Sitefinity HybridForm.

**Comment by ElenaGaneva** [comment] 2018-10-24 11:07
I can't reproduce this with latest versions of Sitefinity 11.0+, so I am closing this issue.

Regards,
Elena

**Closed by ElenaGaneva** 2018-10-24 11:07 UTC
Labels: bug, severity: high, t2
